/**
 * API gateway module.
 *
 * The endpoint catalogue is generated by inspecting the route handlers' own method
 * exports, the health panel calls `/api/v1/health`'s handler in process, and the
 * rate-limit panel reports the live configuration of the shared token-bucket
 * limiter.
 */

import { connection } from "next/server";
import { Activity, Globe, KeyRound, Timer } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { EmptyState } from "@/components/shared/empty-state";
import { KpiCard } from "@/components/shared/kpi-card";
import { PageHeader } from "@/components/shared/page-header";
import { activeOrganizationId } from "@/lib/auth/active-organization";
import { describeLlmMode } from "@/lib/ai/llm/factory";
import { listApiKeys } from "@/lib/data/repositories/security";
import { DEFAULT_RATE_LIMIT, DEFAULT_WINDOW_MS } from "@/lib/api/rate-limit";
import { formatDate, formatDateTime, formatNumber } from "@/lib/format";
import { SETUP_GUIDE_PATH } from "@/lib/i18n/messages";

import { listEndpoints, readHealth } from "./_lib/endpoints";

const METHOD_TONE: Readonly<Record<string, string>> = {
  GET: "border-blue-500/50 text-blue-700 dark:text-blue-300",
  POST: "border-emerald-500/50 text-emerald-700 dark:text-emerald-300",
  PUT: "border-amber-500/50 text-amber-700 dark:text-amber-300",
  PATCH: "border-amber-500/50 text-amber-700 dark:text-amber-300",
  DELETE: "border-red-500/50 text-red-700 dark:text-red-300",
};

function booleanBadge(value: unknown, trueLabel: string, falseLabel: string) {
  return (
    <Badge variant={value === true ? "secondary" : "outline"}>
      {value === true ? trueLabel : falseLabel}
    </Badge>
  );
}

export default async function ApiGatewayPage() {
  await connection();

  const organizationId = await activeOrganizationId();

  const [endpoints, health, apiKeys] = await Promise.all([
    listEndpoints(),
    readHealth(),
    listApiKeys(organizationId),
  ]);

  const configuredLimit = Number(process.env.API_RATE_LIMIT_PER_MINUTE);
  const limit = Number.isFinite(configuredLimit) && configuredLimit > 0
    ? Math.floor(configuredLimit)
    : DEFAULT_RATE_LIMIT;

  const totalOperations = endpoints.reduce(
    (total, endpoint) => total + endpoint.methods.length,
    0,
  );
  const database = (health?.database ?? {}) as Readonly<Record<string, unknown>>;
  const supabase = (health?.supabase ?? {}) as Readonly<Record<string, unknown>>;
  const llmHealth = (health?.llm ?? {}) as Readonly<Record<string, unknown>>;
  const llm = describeLlmMode();

  return (
    <div className="space-y-6">
      <PageHeader
        title="API gateway"
        description="REST surface, API-key authentication, rate limiting and the live health report."
        meta={[
          { label: "Version", value: "v1" },
          { label: "Endpoints", value: formatNumber(endpoints.length) },
          { label: "Operations", value: formatNumber(totalOperations) },
        ]}
      />

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <KpiCard
          title="Endpoints"
          value={formatNumber(endpoints.length)}
          icon={Globe}
          description={`${totalOperations} operations across GET and POST`}
          source="generated from the route handlers' method exports"
        />
        <KpiCard
          title="API keys"
          value={formatNumber(apiKeys.length)}
          icon={KeyRound}
          description={`${apiKeys.filter((key) => key.isActive).length} active`}
          source="listApiKeys()"
        />
        <KpiCard
          title="Rate limit"
          value={formatNumber(limit)}
          unit={`req / ${DEFAULT_WINDOW_MS / 1000}s`}
          icon={Timer}
          description="token bucket, shared per process; a key with rate:unlimited is exempt"
          source="apiRateLimiter"
        />
        <KpiCard
          title="Accepting writes"
          value={health?.writable === true ? "yes" : "no"}
          icon={Activity}
          description={
            health?.writable === true
              ? "a database is reachable"
              : "demo mode: reads are computed, writes are refused"
          }
          source="/api/v1/health"
        />
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Live health report</CardTitle>
          <CardDescription>
            The exact payload <code>GET /api/v1/health</code> returns. It is unauthenticated on
            purpose — &quot;is the deployment misconfigured?&quot; must be answerable before a key
            exists — and reports only *whether* each dependency is configured, never a URL or a
            key.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {health === null ? (
            <EmptyState title="Health handler returned no payload" />
          ) : (
            <>
              <div className="grid gap-3 sm:grid-cols-3">
                <div className="rounded-lg border p-3">
                  <p className="text-xs text-muted-foreground">Database</p>
                  <div className="mt-1 flex flex-wrap gap-1.5">
                    {booleanBadge(database.configured, "configured", "not configured")}
                    <Badge variant="outline">mode {String(database.mode ?? "unknown")}</Badge>
                  </div>
                  {typeof database.fallbackReason === "string" && (
                    <p className="mt-1 font-mono text-[11px] text-muted-foreground">
                      {database.fallbackReason}
                    </p>
                  )}
                </div>
                <div className="rounded-lg border p-3">
                  <p className="text-xs text-muted-foreground">Supabase</p>
                  <div className="mt-1">
                    {booleanBadge(supabase.configured, "configured", "not configured")}
                  </div>
                  <p className="mt-1 text-[11px] text-muted-foreground">
                    Without it, a demo administrator session is used and sign-in is disabled.
                  </p>
                </div>
                <div className="rounded-lg border p-3">
                  <p className="text-xs text-muted-foreground">Language model</p>
                  <div className="mt-1 flex flex-wrap gap-1.5">
                    {booleanBadge(llmHealth.configured, "configured", "not configured")}
                    <Badge variant="outline">{String(llmHealth.model ?? llm.model)}</Badge>
                  </div>
                  <p className="mt-1 text-[11px] text-muted-foreground">
                    {String(llmHealth.labelKo ?? llm.labelKo)}
                  </p>
                </div>
              </div>
              <pre className="overflow-x-auto rounded-lg border bg-muted/40 p-3 text-[11px]">
                {JSON.stringify(health, null, 2)}
              </pre>
            </>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Endpoint catalogue</CardTitle>
          <CardDescription>
            Generated by importing each handler module and listing the HTTP methods it actually
            exports, so this table cannot drift from the implementation. Every response uses the
            same <code>{"{ data, meta }"}</code> / <code>{"{ error }"}</code> envelope.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto rounded-lg border">
            <table className="w-full text-xs">
              <thead className="bg-muted/50">
                <tr>
                  <th className="px-2 py-1.5 text-left font-medium">Path</th>
                  <th className="px-2 py-1.5 text-left font-medium">Methods</th>
                  <th className="px-2 py-1.5 text-left font-medium">Auth</th>
                  <th className="px-2 py-1.5 text-left font-medium">Description</th>
                </tr>
              </thead>
              <tbody>
                {endpoints.map((endpoint) => (
                  <tr key={endpoint.path} className="border-t">
                    <td className="px-2 py-1.5 font-mono">{endpoint.path}</td>
                    <td className="px-2 py-1.5">
                      <div className="flex flex-wrap gap-1">
                        {endpoint.methods.map((method) => (
                          <Badge
                            key={method}
                            variant="outline"
                            className={METHOD_TONE[method] ?? ""}
                          >
                            {method}
                          </Badge>
                        ))}
                      </div>
                    </td>
                    <td className="px-2 py-1.5">
                      <Badge variant={endpoint.authentication === "none" ? "outline" : "secondary"}>
                        {endpoint.authentication}
                      </Badge>
                    </td>
                    <td className="px-2 py-1.5 text-muted-foreground">{endpoint.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Authentication and rate limiting</CardTitle>
            <CardDescription>
              `Authorization: Bearer &lt;apiKey&gt;`, hashed and matched against the `APIKey`
              table with `expiresAt` and `isActive` checked.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-2 text-xs">
            <pre className="overflow-x-auto rounded-lg border bg-muted/40 p-3">
              {`curl -H "Authorization: Bearer <apiKey>" \\
     -H "Content-Type: application/json" \\
     https://<your-host>/api/v1/inventories?reportingYear=2024`}
            </pre>
            <ul className="list-inside list-disc space-y-0.5 text-muted-foreground">
              <li>
                Every response carries <code>X-RateLimit-Limit</code>,{" "}
                <code>X-RateLimit-Remaining</code> and <code>X-RateLimit-Reset</code>.
              </li>
              <li>
                A refused request returns <code>429</code> with <code>Retry-After</code>, always
                at least one second — <code>Retry-After: 0</code> invites a retry that would also
                be refused.
              </li>
              <li>
                The bucket starts full, so a client&apos;s first request is never refused, and
                refills at {formatNumber(limit)} tokens per{" "}
                {DEFAULT_WINDOW_MS / 1000} seconds.
              </li>
              <li>
                Set <code>API_RATE_LIMIT_PER_MINUTE</code> to change the ceiling; the current
                value is {formatNumber(limit)}.
              </li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>API keys</CardTitle>
            <CardDescription>
              Digests are never returned by the repository; only the prefix is shown so a key can
              be identified in a log without being reconstructed.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            {apiKeys.length === 0 ? (
              <EmptyState title="No API keys" />
            ) : (
              apiKeys.map((key) => (
                <div key={key.id} className="rounded-md border p-2.5 text-xs">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="text-sm font-medium">{key.name}</span>
                    <Badge variant="outline" className="font-mono">
                      {key.prefix}…
                    </Badge>
                    <Badge variant={key.isActive ? "secondary" : "destructive"}>
                      {key.isActive ? "active" : "revoked"}
                    </Badge>
                    <span className="ml-auto text-muted-foreground">
                      last used {formatDateTime(key.lastUsedAt)} · expires{" "}
                      {formatDate(key.expiresAt)}
                    </span>
                  </div>
                  <div className="mt-1 flex flex-wrap gap-1">
                    {key.scopes.map((scope) => (
                      <Badge key={scope} variant="outline" className="font-mono">
                        {scope}
                      </Badge>
                    ))}
                  </div>
                </div>
              ))
            )}
            <p className="text-xs text-muted-foreground">
              Issuing a key returns the plaintext exactly once and stores only its digest, so it
              requires a database. The provisioning steps are in <code>{SETUP_GUIDE_PATH}</code>.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
