/**
 * API gateway module.
 *
 * The endpoint catalogue is generated by inspecting the route handlers' own method
 * exports, the health panel calls `/api/v1/health`'s handler in process, and the
 * rate-limit panel reports the live configuration of the shared token-bucket
 * limiter.
 */

import { connection } from "next/server";
import { Activity, Globe, KeyRound, Timer } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { EmptyState } from "@/components/shared/empty-state";
import { KpiCard } from "@/components/shared/kpi-card";
import { PageHeader } from "@/components/shared/page-header";
import { PlanGateLocked } from "@/components/shared/plan-gate";
import { activeOrganizationId } from "@/lib/auth/active-organization";
import { describeLlmMode } from "@/lib/ai/llm/factory";
import { hasModuleAccess } from "@/lib/core/plans";
import { getOrganization } from "@/lib/data/repositories/organization";
import { listApiKeys } from "@/lib/data/repositories/security";
import { DEFAULT_RATE_LIMIT, DEFAULT_WINDOW_MS, rateLimitForKey } from "@/lib/api/rate-limit";
import { formatDate, formatDateTime, formatNumber } from "@/lib/format";
import { SETUP_GUIDE_PATH } from "@/lib/i18n/messages";
import { getDictionary } from "@/lib/i18n/server";

import { listEndpoints, readHealth } from "./_lib/endpoints";

const METHOD_TONE: Readonly<Record<string, string>> = {
  GET: "border-blue-500/50 text-blue-700 dark:text-blue-300",
  POST: "border-emerald-500/50 text-emerald-700 dark:text-emerald-300",
  PUT: "border-amber-500/50 text-amber-700 dark:text-amber-300",
  PATCH: "border-amber-500/50 text-amber-700 dark:text-amber-300",
  DELETE: "border-red-500/50 text-red-700 dark:text-red-300",
};

function booleanBadge(value: unknown, trueLabel: string, falseLabel: string) {
  return (
    <Badge variant={value === true ? "secondary" : "outline"}>
      {value === true ? trueLabel : falseLabel}
    </Badge>
  );
}

export default async function ApiGatewayPage() {
  await connection();
  const dict = await getDictionary();

  const organizationId = await activeOrganizationId();
  const organization = await getOrganization(organizationId);
  if (!hasModuleAccess(organization?.plan ?? "TRIAL", "api-gateway")) {
    return <PlanGateLocked module="api-gateway" />;
  }

  const [endpoints, health, apiKeys] = await Promise.all([
    listEndpoints(),
    readHealth(),
    listApiKeys(organizationId),
  ]);

  const configuredLimit = Number(process.env.API_RATE_LIMIT_PER_MINUTE);
  const limit = Number.isFinite(configuredLimit) && configuredLimit > 0
    ? Math.floor(configuredLimit)
    : DEFAULT_RATE_LIMIT;

  const totalOperations = endpoints.reduce(
    (total, endpoint) => total + endpoint.methods.length,
    0,
  );
  const database = (health?.database ?? {}) as Readonly<Record<string, unknown>>;
  const supabase = (health?.supabase ?? {}) as Readonly<Record<string, unknown>>;
  const llmHealth = (health?.llm ?? {}) as Readonly<Record<string, unknown>>;
  const llm = describeLlmMode();

  return (
    <div className="space-y-6">
      <PageHeader
        title={dict["apiGateway.title"]}
        description={dict["apiGateway.desc"]}
        meta={[
          { label: dict["apiGateway.meta.version"], value: "v1" },
          { label: dict["apiGateway.meta.endpoints"], value: formatNumber(endpoints.length) },
          { label: dict["apiGateway.meta.operations"], value: formatNumber(totalOperations) },
        ]}
      />

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <KpiCard
          title={dict["apiGateway.kpi.endpoints"]}
          value={formatNumber(endpoints.length)}
          icon={Globe}
          description={`${totalOperations} ${dict["apiGateway.kpi.endpointsDesc"]}`}
          source="generated from the route handlers' method exports"
        />
        <KpiCard
          title={dict["apiGateway.kpi.apiKeys"]}
          value={formatNumber(apiKeys.length)}
          icon={KeyRound}
          description={`${apiKeys.filter((key) => key.isActive).length} ${dict["apiGateway.kpi.apiKeysActive"]}`}
          source="listApiKeys()"
        />
        <KpiCard
          title={dict["apiGateway.kpi.rateLimit"]}
          value={formatNumber(limit)}
          unit={`req / ${DEFAULT_WINDOW_MS / 1000}s`}
          icon={Timer}
          description={dict["apiGateway.kpi.rateLimitDesc"]}
          source="apiRateLimiter"
        />
        <KpiCard
          title={dict["apiGateway.kpi.acceptingWrites"]}
          value={health?.writable === true ? dict["apiGateway.kpi.yes"] : dict["apiGateway.kpi.no"]}
          icon={Activity}
          description={
            health?.writable === true
              ? dict["apiGateway.kpi.dbReachable"]
              : dict["apiGateway.kpi.demoMode"]
          }
          source="/api/v1/health"
        />
      </div>

      <Card>
        <CardHeader>
          <CardTitle>{dict["apiGateway.card.liveHealth"]}</CardTitle>
          <CardDescription>
            {dict["apiGateway.card.liveHealthDesc"]}
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {health === null ? (
            <EmptyState title={dict["apiGateway.empty.noHealth"]} />
          ) : (
            <>
              <div className="grid gap-3 sm:grid-cols-3">
                <div className="rounded-lg border p-3">
                  <p className="text-xs text-muted-foreground">{dict["apiGateway.label.database"]}</p>
                  <div className="mt-1 flex flex-wrap gap-1.5">
                    {booleanBadge(database.configured, dict["apiGateway.label.configured"], dict["apiGateway.label.notConfigured"])}
                    <Badge variant="outline">mode {String(database.mode ?? "unknown")}</Badge>
                  </div>
                  {typeof database.fallbackReason === "string" && (
                    <p className="mt-1 font-mono text-[11px] text-muted-foreground">
                      {database.fallbackReason}
                    </p>
                  )}
                </div>
                <div className="rounded-lg border p-3">
                  <p className="text-xs text-muted-foreground">{dict["apiGateway.label.supabase"]}</p>
                  <div className="mt-1">
                    {booleanBadge(supabase.configured, dict["apiGateway.label.configured"], dict["apiGateway.label.notConfigured"])}
                  </div>
                  <p className="mt-1 text-[11px] text-muted-foreground">
                    Without it, a demo administrator session is used and sign-in is disabled.
                  </p>
                </div>
                <div className="rounded-lg border p-3">
                  <p className="text-xs text-muted-foreground">{dict["apiGateway.label.languageModel"]}</p>
                  <div className="mt-1 flex flex-wrap gap-1.5">
                    {booleanBadge(llmHealth.configured, dict["apiGateway.label.configured"], dict["apiGateway.label.notConfigured"])}
                    <Badge variant="outline">{String(llmHealth.model ?? llm.model)}</Badge>
                  </div>
                  <p className="mt-1 text-[11px] text-muted-foreground">
                    {String(llmHealth.labelKo ?? llm.labelKo)}
                  </p>
                </div>
              </div>
              <pre className="overflow-x-auto rounded-lg border bg-muted/40 p-3 text-[11px]">
                {JSON.stringify(health, null, 2)}
              </pre>
            </>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>{dict["apiGateway.card.endpointCatalogue"]}</CardTitle>
          <CardDescription>
            {dict["apiGateway.card.endpointCatalogueDesc"]}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto rounded-lg border">
            <table className="w-full text-xs">
              <thead className="bg-muted/50">
                <tr>
                  <th className="px-2 py-1.5 text-left font-medium">{dict["apiGateway.table.path"]}</th>
                  <th className="px-2 py-1.5 text-left font-medium">{dict["apiGateway.table.methods"]}</th>
                  <th className="px-2 py-1.5 text-left font-medium">{dict["apiGateway.table.auth"]}</th>
                  <th className="px-2 py-1.5 text-left font-medium">{dict["apiGateway.table.description"]}</th>
                </tr>
              </thead>
              <tbody>
                {endpoints.map((endpoint) => (
                  <tr key={endpoint.path} className="border-t">
                    <td className="px-2 py-1.5 font-mono">{endpoint.path}</td>
                    <td className="px-2 py-1.5">
                      <div className="flex flex-wrap gap-1">
                        {endpoint.methods.map((method) => (
                          <Badge
                            key={method}
                            variant="outline"
                            className={METHOD_TONE[method] ?? ""}
                          >
                            {method}
                          </Badge>
                        ))}
                      </div>
                    </td>
                    <td className="px-2 py-1.5">
                      <Badge variant={endpoint.authentication === "none" ? "outline" : "secondary"}>
                        {endpoint.authentication}
                      </Badge>
                    </td>
                    <td className="px-2 py-1.5 text-muted-foreground">{endpoint.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>{dict["apiGateway.card.authAndRateLimit"]}</CardTitle>
            <CardDescription>
              `Authorization: Bearer &lt;apiKey&gt;`, hashed and matched against the `APIKey`
              table with `expiresAt` and `isActive` checked.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-2 text-xs">
            <pre className="overflow-x-auto rounded-lg border bg-muted/40 p-3">
              {`curl -H "Authorization: Bearer <apiKey>" \\
     -H "Content-Type: application/json" \\
     https://<your-host>/api/v1/inventories?reportingYear=2024`}
            </pre>
            <ul className="list-inside list-disc space-y-0.5 text-muted-foreground">
              <li>
                Every response carries <code>X-RateLimit-Limit</code>,{" "}
                <code>X-RateLimit-Remaining</code> and <code>X-RateLimit-Reset</code>.
              </li>
              <li>
                A refused request returns <code>429</code> with <code>Retry-After</code>, always
                at least one second — <code>Retry-After: 0</code> invites a retry that would also
                be refused.
              </li>
              <li>
                The bucket starts full, so a client&apos;s first request is never refused, and
                refills at {formatNumber(limit)} tokens per{" "}
                {DEFAULT_WINDOW_MS / 1000} seconds.
              </li>
              <li>
                Set <code>API_RATE_LIMIT_PER_MINUTE</code> to change the ceiling; the current
                value is {formatNumber(limit)}.
              </li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>{dict["apiGateway.card.apiKeysCard"]}</CardTitle>
            <CardDescription>
              {dict["apiGateway.card.apiKeysCardDesc"]}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            {apiKeys.length === 0 ? (
              <EmptyState title={dict["apiGateway.empty.noApiKeys"]} />
            ) : (
              apiKeys.map((key) => (
                <div key={key.id} className="rounded-md border p-2.5 text-xs">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="text-sm font-medium">{key.name}</span>
                    <Badge variant="outline" className="font-mono">
                      {key.prefix}…
                    </Badge>
                    <Badge variant={key.isActive ? "secondary" : "destructive"}>
                      {key.isActive ? "active" : "revoked"}
                    </Badge>
                    <Badge variant="outline" title={dict["apiGateway.badge.rateLimitTitle"]}>
                      {key.scopes.includes("rate:unlimited")
                        ? dict["apiGateway.badge.unlimited"]
                        : `${formatNumber(rateLimitForKey(key.scopes, key.rateLimitPerMinute))}${dict["apiGateway.badge.perMinuteSuffix"]}${key.rateLimitPerMinute === null ? dict["apiGateway.badge.defaultSuffix"] : ""}`}
                    </Badge>
                    <span className="ml-auto text-muted-foreground">
                      last used {formatDateTime(key.lastUsedAt)} · expires{" "}
                      {formatDate(key.expiresAt)}
                    </span>
                  </div>
                  <div className="mt-1 flex flex-wrap gap-1">
                    {key.scopes.map((scope) => (
                      <Badge key={scope} variant="outline" className="font-mono">
                        {scope}
                      </Badge>
                    ))}
                  </div>
                </div>
              ))
            )}
            <p className="text-xs text-muted-foreground">
              Issuing a key returns the plaintext exactly once and stores only its digest, so it
              requires a database. The provisioning steps are in <code>{SETUP_GUIDE_PATH}</code>.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
