import {
  BookOpen,
  FileText,
  FlaskConical,
  Gauge,
  ListOrdered,
  Sigma,
} from "lucide-react";

import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { ConfidenceBadge } from "@/components/shared/confidence-badge";
import type { Explanation } from "@/lib/ai/explain/build-explanation";
import { formatNumber, formatPercent } from "@/lib/format";

export type ExplanationPanelProps = {
  readonly explanation: Explanation;
  readonly className?: string;
};

function formatInputs(inputs: Readonly<Record<string, number | string | boolean | null>>) {
  const entries = Object.entries(inputs);
  if (entries.length === 0) return "no inputs";
  return entries
    .map(([key, value]) => `${key}=${value === null ? "null" : String(value)}`)
    .join(", ");
}

/**
 * Renders the explainable-AI graph `buildExplanation()` produces: the ordered
 * steps, the verbatim calculation traces, the assumption log, the confidence
 * breakdown and the evidence links.
 *
 * The narrative source is labelled, so deterministic template text is never
 * mistaken for model output — that distinction is the point of decision 8.
 */
export function ExplanationPanel({ explanation, className }: ExplanationPanelProps) {
  const {
    explanation: record,
    steps,
    calculationTraces,
    assumptions,
    confidenceBreakdowns,
    evidenceLinks,
    confidence,
  } = explanation;

  return (
    <Card className={className} data-testid="explanation-panel">
      <CardHeader>
        <div className="flex flex-wrap items-start justify-between gap-2">
          <div className="space-y-1">
            <CardTitle className="flex items-center gap-2 text-base">
              <FlaskConical className="size-4 text-muted-foreground" />
              {record.title}
            </CardTitle>
            <CardDescription>{record.summary}</CardDescription>
          </div>
          <div className="flex flex-wrap items-center gap-1.5">
            <ConfidenceBadge score={confidence?.score ?? record.confidence} level={confidence?.level} />
            <Badge
              variant={explanation.narrativeSource === "llm" ? "secondary" : "outline"}
              title={
                explanation.narrativeSource === "llm"
                  ? `Narrative generated by ${explanation.llmProvider ?? "the configured model"}`
                  : "Narrative generated deterministically from the traces — no model was called"
              }
            >
              {explanation.narrativeSource === "llm"
                ? `narrative: ${explanation.llmModel ?? "llm"}`
                : "narrative: deterministic"}
            </Badge>
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-5 text-sm">
        {record.humanReadable && (
          <section className="space-y-1">
            <h3 className="flex items-center gap-1.5 text-xs font-semibold tracking-wide text-muted-foreground uppercase">
              <BookOpen className="size-3.5" />
              Plain language
            </h3>
            <p className="leading-relaxed">{record.humanReadable}</p>
            {explanation.narrativeError && (
              <p className="text-xs text-amber-700 dark:text-amber-300">
                Narrative generation reported: {explanation.narrativeError}. The numeric
                result is unaffected.
              </p>
            )}
          </section>
        )}

        <section className="space-y-2">
          <h3 className="flex items-center gap-1.5 text-xs font-semibold tracking-wide text-muted-foreground uppercase">
            <ListOrdered className="size-3.5" />
            Steps ({steps.length})
          </h3>
          <ol className="space-y-2" data-testid="explanation-steps">
            {steps.map((step) => (
              <li
                key={step.stepNumber}
                className="rounded-md border p-2.5"
                data-testid={`explanation-step-${step.stepNumber}`}
              >
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <p className="text-sm font-medium">
                    {step.stepNumber}. {step.title}
                  </p>
                  <span className="font-mono text-xs">
                    {formatNumber(step.outputData.value, 4)} {step.outputData.unit}
                  </span>
                </div>
                <p className="text-xs text-muted-foreground">{step.description}</p>
                <p className="mt-1 font-mono text-[11px] break-all text-muted-foreground/90">
                  {formatInputs(step.inputData)}
                </p>
              </li>
            ))}
          </ol>
        </section>

        {calculationTraces.length > 0 && (
          <>
            <Separator />
            <section className="space-y-2">
              <h3 className="flex items-center gap-1.5 text-xs font-semibold tracking-wide text-muted-foreground uppercase">
                <Sigma className="size-3.5" />
                Calculation traces ({calculationTraces.length})
              </h3>
              <ul className="space-y-1">
                {calculationTraces.map((trace) => (
                  <li
                    key={`${trace.orderIndex}-${trace.stepName}`}
                    className="rounded-md bg-muted/50 p-2 font-mono text-[11px] break-all"
                  >
                    <span className="font-sans font-medium">{trace.stepName}</span>
                    {" — "}
                    {trace.formula} = {formatNumber(trace.output, 4)} {trace.unit}
                  </li>
                ))}
              </ul>
            </section>
          </>
        )}

        {assumptions.length > 0 && (
          <>
            <Separator />
            <section className="space-y-2">
              <h3 className="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
                Assumptions ({assumptions.length})
              </h3>
              <ul className="space-y-1.5">
                {assumptions.map((assumption, index) => (
                  <li key={`${index}-${assumption.assumption}`} className="text-xs">
                    <span className="font-medium">{assumption.assumption}</span>
                    {assumption.category && (
                      <Badge variant="outline" className="ml-1.5">
                        {assumption.category}
                      </Badge>
                    )}
                    {assumption.justification && (
                      <span className="block text-muted-foreground">
                        {assumption.justification}
                      </span>
                    )}
                    {assumption.source && (
                      <span className="block text-muted-foreground/80">
                        Source: {assumption.source}
                      </span>
                    )}
                  </li>
                ))}
              </ul>
            </section>
          </>
        )}

        {confidenceBreakdowns.length > 0 && (
          <>
            <Separator />
            <section className="space-y-2">
              <h3 className="flex items-center gap-1.5 text-xs font-semibold tracking-wide text-muted-foreground uppercase">
                <Gauge className="size-3.5" />
                Confidence breakdown
              </h3>
              <ul className="space-y-1">
                {confidenceBreakdowns.map((row) => (
                  <li key={row.factor} className="flex items-center gap-2 text-xs">
                    <span className="w-36 shrink-0 truncate" title={row.description}>
                      {row.factor}
                    </span>
                    <span className="h-1.5 flex-1 overflow-hidden rounded-full bg-muted">
                      <span
                        className="block h-full rounded-full bg-primary"
                        style={{ width: `${Math.min(100, Math.max(0, row.score * 100))}%` }}
                      />
                    </span>
                    <span className="w-24 shrink-0 text-right font-mono">
                      {formatPercent(row.score * 100, 0)} × {formatNumber(row.weight, 2)}
                    </span>
                  </li>
                ))}
              </ul>
            </section>
          </>
        )}

        {evidenceLinks.length > 0 && (
          <>
            <Separator />
            <section className="space-y-1.5">
              <h3 className="flex items-center gap-1.5 text-xs font-semibold tracking-wide text-muted-foreground uppercase">
                <FileText className="size-3.5" />
                Evidence ({evidenceLinks.length})
              </h3>
              <ul className="space-y-1">
                {evidenceLinks.map((link) => (
                  <li key={link.title} className="text-xs">
                    <span className="font-medium">{link.title}</span>
                    <span className="text-muted-foreground"> · {link.type}</span>
                    {link.description && (
                      <span className="block text-muted-foreground">{link.description}</span>
                    )}
                  </li>
                ))}
              </ul>
            </section>
          </>
        )}

        <p className="text-[11px] text-muted-foreground/80">
          Methodology: {record.methodology}
        </p>
      </CardContent>
    </Card>
  );
}
