/**
 * Demo tenant: 24 months of activity data.
 *
 * 16 monthly activity streams x 24 months (Jan 2023 – Dec 2024) = 384 entries,
 * covering all four Scope 1 source types, Scope 2 location *and* market based, and
 * six Scope 3 categories.
 *
 * Quantities are generated by a closed-form seasonal function rather than a random
 * generator, so the dataset is byte-identical on every run, in every environment
 * and in the seeded database:
 *
 *     quantity(year, month) = base x yearFactor(year) x (1 + amplitude x cos(2π(month-1)/12))
 *
 * A positive amplitude peaks in January (heating, boilers), a negative one peaks in
 * July (cooling, refrigerant leakage). `yearFactor` falls 4.5 % in 2024, so the
 * dataset shows a real year-on-year reduction for the trend and target views.
 */

import type {
  CalculationApproach,
  DataQualityLevel,
  DataSourceType,
  GHGScope,
  Scope3Category,
} from "@/lib/core/enums";
import { roundTo } from "@/lib/core/number";
import type { ReportingPeriod } from "@/lib/core/period";
import type { CalculationEntry, Scope1SourceType } from "@/lib/domain/emissions/orchestrator";
import type { ContractualInstrument } from "@/lib/domain/emissions/scope2";
import type { MeasurementType } from "@/lib/domain/quality/score";

import { FACTOR_SECTORS, REGION_APAC, REGION_GLOBAL } from "./emission-factors";
import { DEMO_ORGANIZATION_ID, DEMO_SOURCE_HIERARCHY } from "./organization";

/** Reporting years covered by the fixture, oldest first. */
export const DEMO_REPORTING_YEARS = [2023, 2024] as const;
export const DEMO_BASELINE_YEAR = 2023;
export const DEMO_CURRENT_YEAR = 2024;
export const DEMO_MONTHS_PER_YEAR = 12;
/** 16 streams x 24 months. */
export const DEMO_EXPECTED_ENTRY_COUNT = 384;

/** Activity volume index per reporting year. */
const YEAR_FACTOR: Readonly<Record<number, number>> = {
  2023: 1,
  2024: 0.955,
};

type StreamSpec = {
  readonly key: string;
  readonly emissionSourceId: string;
  readonly label: string;
  readonly scope: GHGScope;
  readonly scope3Category: Scope3Category | null;
  readonly scope1SourceType?: Scope1SourceType;
  readonly approach: CalculationApproach;
  readonly unit: string;
  /** Monthly quantity at the seasonal mean, in `unit`. */
  readonly base: number;
  /** Seasonal amplitude; positive peaks in January, negative in July. */
  readonly amplitude: number;
  readonly decimals: number;
  readonly region: string;
  readonly country: string | null;
  readonly sector: string | null;
  readonly gasTypes?: readonly string[];
  readonly mobileMethod?: "FUEL" | "DISTANCE";
  readonly supplierId?: string;
  readonly measurementType: MeasurementType;
  readonly dataSource: DataSourceType;
  readonly dataQuality: DataQualityLevel;
  readonly isEstimated: boolean;
  readonly hasEvidence: boolean;
  readonly activityDataUncertainty: number;
  readonly methodologyUncertainty: number;
  /** Master-data foreign keys carried by the persisted `ActivityDataEntry`. */
  readonly refs: Readonly<Record<string, string>>;
  /** Contractual instruments, for the market-based Scope 2 streams. */
  readonly instruments?: readonly ContractualInstrument[];
  /** Refrigerant balance, for the fugitive stream. */
  readonly fugitiveBase?: {
    readonly gas?: string;
    readonly blend?: string;
    readonly inventoryChangeShare: number;
    readonly disposalShare: number;
  };
};

const COMBUSTION_GASES = ["CO2", "CH4_FOSSIL", "N2O"] as const;

const STREAMS: readonly StreamSpec[] = [
  // ---------------------------------------------------------------- Scope 1
  {
    key: "s1-ulsan-ng",
    emissionSourceId: "demo-src-ulsan-boiler-ng",
    label: "울산 보일러 LNG 사용량 (Ulsan boiler natural gas)",
    scope: "SCOPE_1",
    scope3Category: null,
    scope1SourceType: "STATIONARY",
    approach: "ACTIVITY_BASED",
    unit: "m3",
    base: 148_000,
    amplitude: 0.22,
    decimals: 0,
    region: REGION_GLOBAL,
    country: null,
    sector: FACTOR_SECTORS.NATURAL_GAS_STATIONARY,
    gasTypes: COMBUSTION_GASES,
    measurementType: "METERED",
    dataSource: "METER_READING",
    dataQuality: "HIGH",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 2,
    methodologyUncertainty: 3,
    refs: { fuelId: "demo-fuel-natural-gas" },
  },
  {
    key: "s1-pyeongtaek-diesel",
    emissionSourceId: "demo-src-pyeongtaek-boiler-diesel",
    label: "평택 보일러 경유 사용량 (Pyeongtaek boiler diesel)",
    scope: "SCOPE_1",
    scope3Category: null,
    scope1SourceType: "STATIONARY",
    approach: "ACTIVITY_BASED",
    unit: "L",
    base: 26_500,
    amplitude: 0.18,
    decimals: 0,
    region: REGION_GLOBAL,
    country: null,
    sector: FACTOR_SECTORS.DIESEL_STATIONARY,
    gasTypes: COMBUSTION_GASES,
    measurementType: "INVOICED",
    dataSource: "INVOICE",
    dataQuality: "HIGH",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 3,
    methodologyUncertainty: 3,
    refs: { fuelId: "demo-fuel-diesel" },
  },
  {
    key: "s1-incheon-mobile",
    emissionSourceId: "demo-src-incheon-fleet-diesel",
    label: "인천 사내차량 경유 사용량 (Incheon on-site fleet diesel)",
    scope: "SCOPE_1",
    scope3Category: null,
    scope1SourceType: "MOBILE",
    approach: "ACTIVITY_BASED",
    unit: "L",
    base: 4_200,
    amplitude: -0.06,
    decimals: 0,
    region: REGION_GLOBAL,
    country: null,
    sector: FACTOR_SECTORS.DIESEL_MOBILE,
    gasTypes: COMBUSTION_GASES,
    mobileMethod: "FUEL",
    measurementType: "INVOICED",
    dataSource: "INVOICE",
    dataQuality: "MEDIUM",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 5,
    methodologyUncertainty: 5,
    refs: { fuelId: "demo-fuel-diesel", vehicleId: "demo-vehicle-forklift" },
  },
  {
    key: "s1-ulsan-fugitive",
    emissionSourceId: "demo-src-ulsan-chiller-r410a",
    label: "울산 칠러 냉매 충전량 (Ulsan chiller refrigerant top-up)",
    scope: "SCOPE_1",
    scope3Category: null,
    scope1SourceType: "FUGITIVE",
    approach: "ACTIVITY_BASED",
    unit: "kg",
    base: 12,
    // Leakage peaks in the July cooling season.
    amplitude: -0.45,
    decimals: 2,
    region: REGION_GLOBAL,
    country: null,
    sector: null,
    measurementType: "INVOICED",
    dataSource: "INVOICE",
    dataQuality: "MEDIUM",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 10,
    methodologyUncertainty: 15,
    refs: { refrigerantId: "demo-refrigerant-r410a", equipmentId: "demo-eq-ulsan-chiller-1" },
    fugitiveBase: {
      blend: "R-410A",
      // The charge stays roughly constant, so everything purchased leaked.
      inventoryChangeShare: 0,
      disposalShare: 0,
    },
  },
  // ------------------------------------------------- Scope 2, location-based
  {
    key: "s2loc-ulsan",
    emissionSourceId: "demo-src-ulsan-electricity",
    label: "울산 구매전력 (Ulsan purchased electricity, location-based)",
    scope: "SCOPE_2_LOCATION",
    scope3Category: null,
    approach: "ACTIVITY_BASED",
    unit: "kWh",
    base: 2_950_000,
    amplitude: 0.1,
    decimals: 0,
    region: REGION_APAC,
    country: "KR",
    sector: null,
    measurementType: "METERED",
    dataSource: "METER_READING",
    dataQuality: "HIGH",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 1,
    methodologyUncertainty: 2,
    refs: { energySourceId: "demo-energy-kepco-grid" },
  },
  {
    key: "s2loc-pyeongtaek",
    emissionSourceId: "demo-src-pyeongtaek-electricity",
    label: "평택 구매전력 (Pyeongtaek purchased electricity, location-based)",
    scope: "SCOPE_2_LOCATION",
    scope3Category: null,
    approach: "ACTIVITY_BASED",
    unit: "kWh",
    base: 1_180_000,
    amplitude: 0.09,
    decimals: 0,
    region: REGION_APAC,
    country: "KR",
    sector: null,
    measurementType: "METERED",
    dataSource: "METER_READING",
    dataQuality: "HIGH",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 1,
    methodologyUncertainty: 2,
    refs: { energySourceId: "demo-energy-kepco-grid" },
  },
  {
    key: "s2loc-incheon",
    emissionSourceId: "demo-src-incheon-electricity",
    label: "인천 구매전력 (Incheon purchased electricity, location-based)",
    scope: "SCOPE_2_LOCATION",
    scope3Category: null,
    approach: "ACTIVITY_BASED",
    unit: "kWh",
    base: 412_000,
    amplitude: -0.14,
    decimals: 0,
    region: REGION_APAC,
    country: "KR",
    sector: null,
    measurementType: "METERED",
    dataSource: "METER_READING",
    dataQuality: "HIGH",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 1,
    methodologyUncertainty: 2,
    refs: { energySourceId: "demo-energy-kepco-grid" },
  },
  // --------------------------------------------------- Scope 2, market-based
  {
    key: "s2mkt-ulsan",
    emissionSourceId: "demo-src-ulsan-electricity",
    label: "울산 구매전력 (Ulsan purchased electricity, market-based)",
    scope: "SCOPE_2_MARKET",
    scope3Category: null,
    approach: "ACTIVITY_BASED",
    unit: "kWh",
    base: 2_950_000,
    amplitude: 0.1,
    decimals: 0,
    region: REGION_APAC,
    country: "KR",
    sector: null,
    measurementType: "METERED",
    dataSource: "METER_READING",
    dataQuality: "HIGH",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 1,
    methodologyUncertainty: 2,
    refs: { energySourceId: "demo-energy-ppa-solar" },
    instruments: [
      {
        id: "demo-instrument-ulsan-solar-ppa",
        type: "PPA",
        quantity: 420_000,
        unit: "kWh",
        co2eKgPerUnit: 0,
      },
    ],
  },
  {
    key: "s2mkt-pyeongtaek",
    emissionSourceId: "demo-src-pyeongtaek-electricity",
    label: "평택 구매전력 (Pyeongtaek purchased electricity, market-based)",
    scope: "SCOPE_2_MARKET",
    scope3Category: null,
    approach: "ACTIVITY_BASED",
    unit: "kWh",
    base: 1_180_000,
    amplitude: 0.09,
    decimals: 0,
    region: REGION_APAC,
    country: "KR",
    sector: null,
    measurementType: "METERED",
    dataSource: "METER_READING",
    dataQuality: "HIGH",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 1,
    methodologyUncertainty: 2,
    refs: { energySourceId: "demo-energy-kepco-grid" },
  },
  {
    key: "s2mkt-incheon",
    emissionSourceId: "demo-src-incheon-electricity",
    label: "인천 구매전력 (Incheon purchased electricity, market-based)",
    scope: "SCOPE_2_MARKET",
    scope3Category: null,
    approach: "ACTIVITY_BASED",
    unit: "kWh",
    base: 412_000,
    amplitude: -0.14,
    decimals: 0,
    region: REGION_APAC,
    country: "KR",
    sector: null,
    measurementType: "METERED",
    dataSource: "METER_READING",
    dataQuality: "HIGH",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 1,
    methodologyUncertainty: 2,
    refs: { energySourceId: "demo-energy-kepco-grid" },
    instruments: [
      {
        id: "demo-instrument-incheon-irec",
        type: "I_REC",
        quantity: 120_000,
        unit: "kWh",
        co2eKgPerUnit: 0,
      },
    ],
  },
  // ---------------------------------------------------------------- Scope 3
  {
    key: "s3c1-resin",
    emissionSourceId: "demo-src-cat1-resin",
    label: "구매 수지 원료 (Purchased polymer resin)",
    scope: "SCOPE_3",
    scope3Category: "CAT_1_PURCHASED_GOODS",
    // Average-data arithmetic (mass x factor) against a *supplier-specific*
    // factor. The SUPPLIER_SPECIFIC approach means a supplier-reported CO2e
    // total, which this stream does not have.
    approach: "AVERAGE_DATA",
    unit: "t",
    base: 1_640,
    amplitude: 0.07,
    decimals: 1,
    region: REGION_APAC,
    country: "KR",
    sector: FACTOR_SECTORS.POLYMER,
    supplierId: "demo-supplier-resin",
    measurementType: "INVOICED",
    dataSource: "ERP_SYSTEM",
    dataQuality: "HIGH",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 3,
    methodologyUncertainty: 12,
    refs: { supplierId: "demo-supplier-resin", rawMaterialId: "demo-material-pp-resin" },
  },
  {
    key: "s3c3-wtt",
    emissionSourceId: "demo-src-cat3-wtt-electricity",
    label: "전력 상류배출 활동량 (Purchased electricity, WTT basis)",
    scope: "SCOPE_3",
    scope3Category: "CAT_3_FUEL_ENERGY",
    approach: "ACTIVITY_BASED",
    unit: "kWh",
    base: 4_542_000,
    amplitude: 0.08,
    decimals: 0,
    region: REGION_GLOBAL,
    country: null,
    sector: FACTOR_SECTORS.ENERGY_UPSTREAM,
    measurementType: "CALCULATED",
    dataSource: "CALCULATED",
    dataQuality: "MEDIUM",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 2,
    methodologyUncertainty: 20,
    refs: { energySourceId: "demo-energy-kepco-grid" },
  },
  {
    key: "s3c4-freight",
    emissionSourceId: "demo-src-cat4-inbound-freight",
    label: "상류 물류 활동량 (Upstream inbound freight)",
    scope: "SCOPE_3",
    scope3Category: "CAT_4_UPSTREAM_TRANSPORT",
    approach: "ACTIVITY_BASED",
    unit: "tkm",
    base: 985_000,
    amplitude: 0.08,
    decimals: 0,
    region: REGION_GLOBAL,
    country: null,
    sector: FACTOR_SECTORS.ROAD_FREIGHT,
    measurementType: "INVOICED",
    dataSource: "API_INTEGRATION",
    dataQuality: "MEDIUM",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 8,
    methodologyUncertainty: 25,
    refs: {
      supplierId: "demo-supplier-freight",
      logisticsRouteId: "demo-route-ulsan-incheon",
    },
  },
  {
    key: "s3c5-waste",
    emissionSourceId: "demo-src-cat5-waste",
    label: "사업장 폐기물 배출량 (Operational waste sent for treatment)",
    scope: "SCOPE_3",
    scope3Category: "CAT_5_WASTE",
    approach: "ACTIVITY_BASED",
    unit: "t",
    base: 142,
    amplitude: 0.05,
    decimals: 2,
    region: REGION_GLOBAL,
    country: null,
    sector: FACTOR_SECTORS.WASTE_TREATMENT,
    measurementType: "INVOICED",
    dataSource: "INVOICE",
    dataQuality: "MEDIUM",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 6,
    methodologyUncertainty: 30,
    refs: { supplierId: "demo-supplier-waste", wasteTypeId: "demo-waste-plastic-scrap" },
  },
  {
    key: "s3c6-travel",
    emissionSourceId: "demo-src-cat6-business-travel",
    label: "임직원 출장 (Business travel, air)",
    scope: "SCOPE_3",
    scope3Category: "CAT_6_BUSINESS_TRAVEL",
    approach: "ACTIVITY_BASED",
    unit: "pkm",
    base: 96_000,
    amplitude: -0.12,
    decimals: 0,
    region: REGION_GLOBAL,
    country: null,
    sector: FACTOR_SECTORS.AIR_TRAVEL,
    measurementType: "INVOICED",
    dataSource: "API_INTEGRATION",
    dataQuality: "MEDIUM",
    isEstimated: false,
    hasEvidence: true,
    activityDataUncertainty: 5,
    methodologyUncertainty: 25,
    refs: {},
  },
  {
    key: "s3c7-commuting",
    emissionSourceId: "demo-src-cat7-commuting",
    label: "임직원 통근 (Employee commuting)",
    scope: "SCOPE_3",
    scope3Category: "CAT_7_EMPLOYEE_COMMUTING",
    approach: "AVERAGE_DATA",
    unit: "pkm",
    base: 268_000,
    amplitude: 0.03,
    decimals: 0,
    region: REGION_GLOBAL,
    country: null,
    sector: FACTOR_SECTORS.COMMUTING_CAR,
    measurementType: "ESTIMATED",
    dataSource: "ESTIMATED",
    dataQuality: "LOW",
    isEstimated: true,
    hasEvidence: false,
    activityDataUncertainty: 25,
    methodologyUncertainty: 30,
    refs: {},
  },
];

/** Streams, exported so the seed and the UI can enumerate them. */
export const DEMO_ACTIVITY_STREAMS = STREAMS;

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

function monthPeriod(year: number, month: number): ReportingPeriod {
  return {
    start: new Date(Date.UTC(year, month - 1, 1)),
    // Last instant of the month, expressed as the last day at 00:00 UTC.
    end: new Date(Date.UTC(year, month, 0)),
  };
}

function seasonalQuantity(spec: StreamSpec, year: number, month: number): number {
  const seasonal = 1 + spec.amplitude * Math.cos((2 * Math.PI * (month - 1)) / 12);
  return roundTo(spec.base * (YEAR_FACTOR[year] ?? 1) * seasonal, spec.decimals);
}

/** `ActivityData` header rows: one per stream per reporting year. */
export type DemoActivityData = {
  readonly id: string;
  readonly organizationId: string;
  readonly facilityId: string | null;
  readonly businessUnitId: string | null;
  readonly name: string;
  readonly description: string;
  readonly scope: GHGScope;
  readonly scope3Category: Scope3Category | null;
  readonly reportingYear: number;
  readonly reportingMonth: null;
  readonly dataSource: DataSourceType;
  readonly dataQuality: DataQualityLevel;
  readonly isVerified: boolean;
};

/** `ActivityDataEntry` rows, shaped for persistence. */
export type DemoActivityDataEntry = {
  readonly id: string;
  readonly activityDataId: string;
  readonly emissionSourceId: string;
  readonly quantity: number;
  readonly unit: string;
  readonly startDate: Date;
  readonly endDate: Date;
  readonly notes: string;
  readonly evidenceUrl: string | null;
  readonly isEstimated: boolean;
  /** Relative uncertainty as a 0..1 fraction, matching the Prisma column. */
  readonly uncertainty: number;
  readonly productId: string | null;
  readonly supplierId: string | null;
  readonly vehicleId: string | null;
  readonly fuelId: string | null;
  readonly refrigerantId: string | null;
  readonly rawMaterialId: string | null;
  readonly logisticsRouteId: string | null;
  readonly energySourceId: string | null;
  readonly wasteTypeId: string | null;
  readonly waterSourceId: string | null;
};

function activityDataId(spec: StreamSpec, year: number): string {
  return `demo-ad-${spec.key}-${year}`;
}

function entryId(spec: StreamSpec, year: number, month: number): string {
  return `demo-ade-${spec.key}-${year}-${String(month).padStart(2, "0")}`;
}

function buildActivityData(): readonly DemoActivityData[] {
  const rows: DemoActivityData[] = [];
  for (const spec of STREAMS) {
    const hierarchy = DEMO_SOURCE_HIERARCHY[spec.emissionSourceId];
    for (const year of DEMO_REPORTING_YEARS) {
      rows.push({
        id: activityDataId(spec, year),
        organizationId: DEMO_ORGANIZATION_ID,
        facilityId: hierarchy.facilityId,
        businessUnitId: hierarchy.businessUnitId,
        name: `${spec.label} ${year}`,
        description: `Monthly ${spec.unit} readings for ${year}.`,
        scope: spec.scope,
        scope3Category: spec.scope3Category,
        reportingYear: year,
        reportingMonth: null,
        dataSource: spec.dataSource,
        dataQuality: spec.dataQuality,
        // The prior year has completed its assurance cycle.
        isVerified: year === DEMO_BASELINE_YEAR,
      });
    }
  }
  return rows;
}

function buildEntries(): readonly DemoActivityDataEntry[] {
  const rows: DemoActivityDataEntry[] = [];
  for (const spec of STREAMS) {
    for (const year of DEMO_REPORTING_YEARS) {
      for (let month = 1; month <= DEMO_MONTHS_PER_YEAR; month += 1) {
        const period = monthPeriod(year, month);
        rows.push({
          id: entryId(spec, year, month),
          activityDataId: activityDataId(spec, year),
          emissionSourceId: spec.emissionSourceId,
          quantity: seasonalQuantity(spec, year, month),
          unit: spec.unit,
          startDate: period.start,
          endDate: period.end,
          notes: `${spec.label} — ${year}-${String(month).padStart(2, "0")}`,
          evidenceUrl: spec.hasEvidence
            ? `https://example.com/hanbit-materials/evidence/${spec.key}/${year}-${String(month).padStart(2, "0")}.pdf`
            : null,
          isEstimated: spec.isEstimated,
          uncertainty: roundTo(spec.activityDataUncertainty / 100, 4),
          productId: spec.refs.productId ?? null,
          supplierId: spec.refs.supplierId ?? null,
          vehicleId: spec.refs.vehicleId ?? null,
          fuelId: spec.refs.fuelId ?? null,
          refrigerantId: spec.refs.refrigerantId ?? null,
          rawMaterialId: spec.refs.rawMaterialId ?? null,
          logisticsRouteId: spec.refs.logisticsRouteId ?? null,
          energySourceId: spec.refs.energySourceId ?? null,
          wasteTypeId: spec.refs.wasteTypeId ?? null,
          waterSourceId: spec.refs.waterSourceId ?? null,
        });
      }
    }
  }
  return rows;
}

export const DEMO_ACTIVITY_DATA: readonly DemoActivityData[] = buildActivityData();
export const DEMO_ACTIVITY_ENTRIES: readonly DemoActivityDataEntry[] = buildEntries();

// ---------------------------------------------------------------------------
// Projection onto the orchestrator input
// ---------------------------------------------------------------------------

const STREAM_BY_ENTRY_ID: ReadonlyMap<string, StreamSpec> = new Map(
  STREAMS.flatMap((spec) =>
    DEMO_REPORTING_YEARS.flatMap((year) =>
      Array.from({ length: DEMO_MONTHS_PER_YEAR }, (_, index) => {
        const month = index + 1;
        return [entryId(spec, year, month), spec] as const;
      }),
    ),
  ),
);

/**
 * Projects a persisted entry onto the `CalculationEntry` the orchestrator takes.
 * The hierarchy ids are denormalised here — exactly the join the data layer does
 * for real database rows.
 */
export function toCalculationEntry(entry: DemoActivityDataEntry): CalculationEntry {
  const spec = STREAM_BY_ENTRY_ID.get(entry.id);
  if (!spec) {
    throw new Error(`No demo activity stream registered for entry ${entry.id}`);
  }
  const hierarchy = DEMO_SOURCE_HIERARCHY[spec.emissionSourceId];

  return {
    id: entry.id,
    name: entry.notes,
    quantity: entry.quantity,
    unit: entry.unit,
    dataPeriod: { start: entry.startDate, end: entry.endDate },
    scope: spec.scope,
    scope3Category: spec.scope3Category,
    scope1SourceType: spec.scope1SourceType,
    approach: spec.approach,
    region: spec.region,
    country: spec.country,
    sector: spec.sector,
    supplierId: spec.supplierId ?? null,
    gasTypes: spec.gasTypes,
    businessUnitId: hierarchy.businessUnitId,
    facilityId: hierarchy.facilityId,
    buildingId: hierarchy.buildingId,
    productionLineId: hierarchy.productionLineId,
    equipmentId: hierarchy.equipmentId,
    emissionSourceId: hierarchy.emissionSourceId,
    mobileMethod: spec.mobileMethod,
    fugitive: spec.fugitiveBase
      ? {
          method: "SCREENING",
          blend: spec.fugitiveBase.blend,
          gas: spec.fugitiveBase.gas as never,
          inventoryChange: roundTo(entry.quantity * spec.fugitiveBase.inventoryChangeShare, 3),
          purchases: entry.quantity,
          disposals: roundTo(entry.quantity * spec.fugitiveBase.disposalShare, 3),
        }
      : undefined,
    market: spec.instruments ? { instruments: spec.instruments } : undefined,
    measurementType: spec.measurementType,
    isEstimated: spec.isEstimated,
    hasEvidence: spec.hasEvidence,
    unitConsistent: true,
    sourceConsistentWithPriorPeriod: true,
    methodConsistentWithPriorPeriod: true,
    activityDataUncertainty: spec.activityDataUncertainty,
    methodologyUncertainty: spec.methodologyUncertainty,
  };
}

/** Every fixture entry, projected for the orchestrator. */
export const DEMO_CALCULATION_ENTRIES: readonly CalculationEntry[] =
  DEMO_ACTIVITY_ENTRIES.map(toCalculationEntry);

/** Entries whose data period falls inside the requested reporting year. */
export function demoEntriesForYear(year: number): readonly CalculationEntry[] {
  return DEMO_CALCULATION_ENTRIES.filter(
    (entry) => entry.dataPeriod?.start.getUTCFullYear() === year,
  );
}

/** Full-year reporting period for a calendar reporting year. */
export function demoPeriodForYear(year: number): ReportingPeriod {
  return {
    start: new Date(Date.UTC(year, 0, 1)),
    end: new Date(Date.UTC(year, 11, 31)),
  };
}

/** Total activity quantity per unit, used by the seed-parity test. */
export function demoActivityTotals(): Readonly<Record<string, number>> {
  const totals: Record<string, number> = {};
  for (const entry of DEMO_ACTIVITY_ENTRIES) {
    const key = `${entry.emissionSourceId}:${entry.unit}`;
    totals[key] = roundTo((totals[key] ?? 0) + entry.quantity, 4);
  }
  return totals;
}
