/**
 * DOCX export using the `docx` library (already a devDependency).
 *
 * Produces a Word document with:
 * - Cover section with metadata
 * - Section-per-category with tabulated datapoints
 */

import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  VerticalAlign,
  WidthType,
} from "docx";

import type { ExportInput } from "./types";

/**
 * Generate a DOCX buffer from the given export input.
 */
export async function generateDocx(input: ExportInput): Promise<Buffer> {
  const doc = new Document({
    creator: "CIOS",
    title: `${input.metadata.framework} Report - ${input.metadata.reportingYear}`,
    description: "ESG Disclosure Report generated by CIOS",
    sections: [
      {
        children: [
          new Paragraph({
            text: "ESG Disclosure Report",
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: input.metadata.framework,
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({
            children: [
              new TextRun({ text: "조직명: ", bold: true }),
              new TextRun(input.metadata.organizationName),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "보고연도: ", bold: true }),
              new TextRun(String(input.metadata.reportingYear)),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "생성일시: ", bold: true }),
              new TextRun(input.metadata.generatedAt),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "완성도: ", bold: true }),
              new TextRun(
                `${(input.metadata.completeness * 100).toFixed(1)}%`,
              ),
            ],
          }),
          new Paragraph({ text: "" }),
          // Sections
          ...input.sections.flatMap((section) => [
            new Paragraph({
              text: section.title,
              heading: HeadingLevel.HEADING_2,
            }),
            new Table({
              width: { size: 100, type: WidthType.PERCENTAGE },
              rows: [
                new TableRow({
                  tableHeader: true,
                  children: ["요구사항", "유형", "응답", "출처"].map(
                    (header) =>
                      new TableCell({
                        verticalAlign: VerticalAlign.CENTER,
                        children: [
                          new Paragraph({
                            children: [
                              new TextRun({ text: header, bold: true }),
                            ],
                          }),
                        ],
                      }),
                  ),
                }),
                ...section.rows.map(
                  (row) =>
                    new TableRow({
                      children: [
                        new TableCell({
                          children: [new Paragraph(row.requirement)],
                        }),
                        new TableCell({
                          children: [new Paragraph(row.dataType)],
                        }),
                        new TableCell({
                          children: [
                            new Paragraph(
                              row.response !== null &&
                                row.response !== undefined
                                ? String(row.response)
                                : "",
                            ),
                          ],
                        }),
                        new TableCell({
                          children: [
                            new Paragraph(
                              row.source === "auto"
                                ? "자동"
                                : row.source === "narrative"
                                  ? "서술"
                                  : "미응답",
                            ),
                          ],
                        }),
                      ],
                    }),
                ),
              ],
            }),
            new Paragraph({ text: "" }),
          ]),
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}
